const traitInputAttr = { placeholder: '例: ここにテキスト' };

export default {
  assetManager: {
    addButton: '画像を追加',
    inputPlh: 'http://画像のパス',
    modalTitle: '画像を選択',
    uploadTitle: 'ここにファイルをドロップするか、クリックしてアップロード',
  },
  blockManager: {
    labels: {
      // 'block-id': 'ブロックラベル',
    },
    categories: {
      // 'category-id': 'カテゴリーラベル',
    },
  },
  domComponents: {
    names: {
      '': 'ボックス',
      wrapper: 'ボディ',
      text: 'テキスト',
      comment: 'コメント',
      image: '画像',
      video: 'ビデオ',
      label: 'ラベル',
      link: 'リンク',
      map: 'マップ',
      tfoot: 'テーブルフッター',
      tbody: 'テーブルボディ',
      thead: 'テーブルヘッド',
      table: 'テーブル',
      row: 'テーブル行',
      cell: 'テーブルセル',
    },
  },
  deviceManager: {
    device: 'デバイス',
    devices: {
      desktop: 'デスクトップ',
      tablet: 'タブレット',
      mobileLandscape: 'モバイル (横向き)',
      mobilePortrait: 'モバイル (縦向き)',
    },
  },
  panels: {
    buttons: {
      titles: {
        preview: 'プレビュー',
        fullscreen: 'フルスクリーン',
        'sw-visibility': 'コンポーネント表示',
        'export-template': 'コードを表示',
        'open-sm': 'スタイルマネージャを開く',
        'open-tm': '設定',
        'open-layers': 'レイヤーマネージャを開く',
        'open-blocks': 'ブロックを開く',
      },
    },
  },
  selectorManager: {
    label: 'クラス',
    selected: '選択済み',
    emptyState: '- ステート -',
    states: {
      hover: 'ホバー',
      active: 'クリック',
      'nth-of-type(2n)': '偶数/奇数',
    },
  },
  styleManager: {
    empty: 'スタイルマネージャを使用する前に要素を選択してください',
    layer: 'レイヤー',
    fileButton: '画像',
    sectors: {
      general: '一般',
      layout: 'レイアウト',
      typography: 'タイポグラフィ',
      decorations: '装飾',
      extra: '追加',
      flex: 'フレックス',
      dimension: 'サイズ',
    },
    properties: {
      'text-shadow-h': 'X',
      'text-shadow-v': 'Y',
      'text-shadow-blur': 'ぼかし',
      'text-shadow-color': '色',
      'box-shadow-h': 'X',
      'box-shadow-v': 'Y',
      'box-shadow-blur': 'ぼかし',
      'box-shadow-spread': '広がり',
      'box-shadow-color': '色',
      'box-shadow-type': 'タイプ',
      'margin-top-sub': '上',
      'margin-right-sub': '右',
      'margin-bottom-sub': '下',
      'margin-left-sub': '左',
      'padding-top-sub': '上',
      'padding-right-sub': '右',
      'padding-bottom-sub': '下',
      'padding-left-sub': '左',
      'border-width-sub': '幅',
      'border-style-sub': 'スタイル',
      'border-color-sub': '色',
      'border-top-left-radius-sub': '左上',
      'border-top-right-radius-sub': '右上',
      'border-bottom-right-radius-sub': '右下',
      'border-bottom-left-radius-sub': '左下',
      'transform-rotate-x': '回転X',
      'transform-rotate-y': '回転Y',
      'transform-rotate-z': '回転Z',
      'transform-scale-x': 'スケールX',
      'transform-scale-y': 'スケールY',
      'transform-scale-z': 'スケールZ',
      'transition-property-sub': 'プロパティ',
      'transition-duration-sub': '期間',
      'transition-timing-function-sub': 'タイミング',
      'background-image-sub': '画像',
      'background-repeat-sub': '繰り返し',
      'background-position-sub': '位置',
      'background-attachment-sub': '固定',
      'background-size-sub': 'サイズ',
    },
  },
  traitManager: {
    empty: 'トレイトマネージャを使用する前に要素を選択してください',
    label: 'コンポーネント設定',
    traits: {
      labels: {
        // id: 'ID',
        // alt: '代替テキスト',
        // title: 'タイトル',
        // href: 'リンク先',
      },
      attributes: {
        id: traitInputAttr,
        alt: traitInputAttr,
        title: traitInputAttr,
        href: { placeholder: '例: https://google.com' },
      },
      options: {
        target: {
          false: 'このウィンドウ',
          _blank: '新しいウィンドウ',
        },
      },
    },
  },
  storageManager: {
    recover: '保存されていない変更を復元しますか？',
  },
};
